spring.application.name=demo

spring.datasource.url=${jbc:postgresql://dpg-d8h89qeq1p3s73fsc2sg-a.frankfurt-postgres.render.com/flashcards_2xaa}
spring.datasource.username=${flashcards_r8eb_user}
spring.datasource.password=${aiL7zSsILyly3NOnEgt8NpX3KJZYUpDp}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect